export declare const PC_MAX_BROWSER_WIDTH = 1709;
export declare const TABLET_MAX_BROWSER_WIDTH = 1023;
export declare const MOBILE_MAX_BROWSER_WIDTH = 767;
export declare const PC_WIDTH: string;
export declare const WIDE_PC_GLOBAL_PADDING = 32;
export declare const PC_GLOBAL_PADDING = 32;
export declare const TABLET_GLOBAL_PADDING = 32;
export declare const MOBILE_GLOBAL_PADDING = 20;
export declare const WIDE_PC_MAX_LAYOUT_SYSTEM_WIDTH = 1555;
export declare const PC_MAX_LAYOUT_SYSTEM_WIDTH = 1240;
export declare const TABLET_MAX_LAYOUT_SYSTEM_WIDTH: number;
export declare const MOBILE_MAX_LAYOUT_SYSTEM_WIDTH: number;
export declare const WIDE_PC_COLUMNS = 15;
export declare const PC_COLUMNS = 12;
export declare const TABLET_COLUMNS = 8;
export declare const MOBILE_COLUMNS = 6;
export declare const WIDE_PC_GUTTER = 20;
export declare const PC_GUTTER = 20;
export declare const TABLET_GUTTER = 16;
export declare const MOBILE_GUTTER = 16;
export declare const PC_1600_RAW = 1600;
export declare const PC_1600: string;
export declare const PC_1400_RAW = 1400;
export declare const PC_1400: string;
export declare const PC_1200_RAW = 1200;
export declare const PC_1200: string;
export declare const PC_1130_RAW = 1130;
export declare const PC_1130: string;
export declare const TABLET_WIDTH_RAW = 1023;
export declare const TABLET_WIDTH: string;
export declare const MOBILE_WIDTH_RAW = 767;
export declare const MOBILE_WIDTH: string;
export declare const MOBILE_SMALL_WIDTH_RAW = 415;
export declare const MOBILE_SMALL_WIDTH: string;
export declare const MOBLIE_SMALLEST_WIDTH_RAW = 374;
export declare const MOBILE_SMALLEST_WIDTH: string;
